version: '3.2'
services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile.workspace
    image: ndp-workspace
  server:
    depends_on:
      - workspace
    build:
      context: services/server
      dockerfile: Dockerfile
    image: ndp-server
    command: node .
    ports:
      - "4000:4000"
    volumes:
      - ./services/server:/app/services/server
      - hidden:/app/services/server/node_modules
  ui:
    depends_on:
      - workspace
    build:
      context: services/ui
      dockerfile: Dockerfile
    image: ndp-ui
    volumes:
      - ./services/ui:/app/services/ui
      - hidden:/app/services/ui/node_modules

volumes:
  hidden:
