version: '3.2'
services:
  workspace:
    build:
      dockerfile: Dockerfile.workspace
    image: ndp-workspace:dev
  server:
    build:
      dockerfile: Dockerfile.dev
    image: ndp-server:dev
    command: yarn start
  ui:
    build:
      dockerfile: Dockerfile.dev
    image: ndp-ui:dev
    ports:
      - "5000:5000"
    command: yarn start
