# STAGE 1: Loading Image lagoon-node-packages-builder which contains node packages shared by all Node Services
FROM ndp-workspace AS workspace

# STAGE 2: specific service Image
FROM node:8

# Copying generated node_modules from the first stage
COPY --from=workspace /app /app

# Setting the workdir to the service, all following commands will run from here
WORKDIR /app/services/server/
COPY . .
# Running yarn install in case some dependencies are not here
RUN yarn --frozen-lockfile
ENV NODE_ENV development
CMD ["yarn", "start"]
